FROM openjdk:8-jdk-alpine
MAINTAINER tanyp dev.tanyp@qq.com
VOLUME /tmp
COPY simple-provider-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8051
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]