spring:
  application:
    name: simple-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3306/simple?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
server:
  port: 8051
